name:  CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
         docker build . --file Dockerfile --tag my-image-name:${BUILD_NUMBER}
          
      - name: Deploy Application & Database 
        run: |
          docker-compose up -d


# build-${{ github.run_number }}
